version = 1

test_patterns = ["test/**"]

[[analyzers]]
name = "test-coverage"
enabled = false

[[analyzers]]
name = "shell"
enabled = false

[[analyzers]]
name = "python"
enabled = false

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120

[[transformers]]
name = "autopep8"
enabled = false
